### ISSUE TITLE
Add Makefile for CI/CD support

### ISSUE THREAD

**Issue by feliun** [guidesmiths/generator-systemic#13]

**Comment by kevinccbsg** [comment]
@UlisesGascon @feliun I think we are using Travis now https://github.com/guidesmiths/generator-systemic/blob/master/.travis.yml should we close this issue?

**Comment by feliun** [comment]
@kevinccbsg this ticket is not about building this project with CI/CD. Instead, it's about adding a Makefile inside the generator so every time we create a new service it will be generated with a default Makefile preconfigured to easily plug it to any CI server

**Comment by feliun** [comment]
example: https://github.com/feliun/microservices-school/blob/master/Makefile

**Comment by MatteoDiPaolo** [comment]
@feliun @UlisesGascon @kevinccbsg I have come up with a first **makefile** draft using the example provided by @feliun .

Here it is: [_makefile](https://github.com/guidesmiths/generator-systemic/blob/issue%2313/generators/app/templates/root/_makefile)

It has a bunch of recipes that may be used during the CI phase even if is lacking things like code quality checks (e.g. sonarqube) and security checks (@UlisesGascon any idea on this?)
All these recipes are related to the CI phase and there is nothing still about the CD.

Actually it is kind difficult to come up with a list of recipes general enough to be useful in different CI/CD tools (e.g. travis, jenkins, azure, etc.)

Any feedback is more than welcome, let's try to come up with a clear definition of how this makefile should look like.

**Comment by feliun** [comment]
@MatteoDiPaolo I am in favour of keeping it very simple initially, so I'd remove https://github.com/guidesmiths/generator-systemic/blob/issue%2313/generators/app/templates/root/_makefile#L24-L36

Also in here https://github.com/guidesmiths/generator-systemic/blob/issue%2313/generators/app/templates/root/_makefile#L18-L22 I'd just run `npm run qa`

Re. creating the yml file for the right CI server, I wouldn't bother. We just create an off-the-shell very lean Makefile that you could plug into a CI right away yourself or you could just ignore.
