### ISSUE TITLE
Add deploy capabilities in systemic generator

### ISSUE THREAD

**Issue by servatj** [guidesmiths/generator-systemic#6]
We want a service ready to deploy right after the minimal systemic is generated.

**Comment by feliun** [comment]
Actually we would like a Dockerfile and a npm script to build the docker image out of the box. The "demo effect" would be "yo systemic + npm run build" === docker ready to deploy!

**Comment by MatteoDiPaolo** [comment]
Closing since the [makefile](https://github.com/guidesmiths/generator-systemic/blob/master/generators/app/templates/root/_makefile) is already taking care of this.
